### ISSUE TITLE
Problem initializing?

### ISSUE THREAD

**Issue by miketwo** [davisagli/SublimePythonCoverage#13]
Came across this error when trying to load it:

Reloading plugin /home/cosmogia/.config/sublime-text-2/Packages/Python Coverage/SublimePythonCoverage.py
SublimePythonCoverage installing coverage.py.
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./SublimePythonCoverage.py", line 16, in <module>
    payload = urllib.urlopen(SOURCE).read()
  File ".\urllib.py", line 86, in urlopen
  File ".\urllib.py", line 205, in open
  File ".\urllib.py", line 360, in open_http
  File ".\urllib.py", line 373, in http_error
  File ".\urllib.py", line 657, in http_error_301
  File ".\urllib.py", line 638, in http_error_302
  File ".\urllib.py", line 653, in redirect_internal
  File ".\urllib.py", line 202, in open
  File ".\urllib.py", line 214, in open_unknown
IOError: [Errno url error] unknown url type: 'https'

**Comment by monostop** [comment]
I have the same problem

**Comment by davisagli** [comment]
Sounds like the Python used by Sublime isn't compiled with SSL support.

**Comment by monostop** [comment]
I think that's the case for linux. But on the other hand, the source is a http url so I don't understand why this is a problem.

**Comment by davisagli** [comment]
PyPI now only supports downloading packages over https, so it's redirecting to an https url.

**Comment by davisagli** [comment]
Maybe it would be better to just bundle the coverage tarball with this plugin.

**Comment by nathforge** [comment]
Can workaround this on Linux by fetching the package via shell, e.g:

``` shell
cd ~/.config/sublime-text-2/Packages/Python\ Coverage
wget http://pypi.python.org/packages/source/c/coverage/coverage-3.5.2.tar.gz
tar -xzvf coverage-3.5.2.tar.gz coverage-3.5.2
mv coverage-3.5.2/coverage/ .
rm -rf coverage-3.5.2*
touch SublimePythonCoverage.py # Tell Sublime to reload the plugin
```
